language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jazsingh05-github"
    token:
      secure: "a8a6edda7de1fdd9a355d4df3af36255c180e368"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
